# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    DuelsProcessRunEndQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: duels-process-run-end-queue
            VisibilityTimeout: 601
    DuelsProcessRunEndSqsQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Id: DuelsProcessRunEndQueuePolicy
                Statement:
                    - Sid: Allow-SNS-SendMessage
                      Effect: Allow
                      Principal:
                          AWS: '*'
                      Action:
                          - sqs:SendMessage
                      Resource: !GetAtt DuelsProcessRunEndQueue.Arn
                      Condition:
                          ArnEquals:
                              aws:SourceArn: arn:aws:sns:us-west-2:478062583808:duels-run-end-published
            Queues:
                - !Ref DuelsProcessRunEndQueue
    SnsSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Protocol: SQS
            Endpoint: !GetAtt DuelsProcessRunEndQueue.Arn
            TopicArn: arn:aws:sns:us-west-2:478062583808:duels-run-end-published

    ProcessDuelsRunEndFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-duels-run-end.default
            Runtime: nodejs12.x
            CodeUri: ./dist/process-duels-run-end
            MemorySize: 192
            Timeout: 40
            ReservedConcurrentExecutions: 1
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-duels-run-end
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt DuelsProcessRunEndQueue.Arn
